### ISSUE TITLE
Incompatibility error after Atom update

### ISSUE THREAD

**Issue by hallaathrad** [Fred-Barclay/Termination#56]
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
pty.js@0.3.0 – Cannot find module '..\bin\win32\x64.m53.node'

Similar error for platformio-IDE (complaining about pty.js)

Atom: 1.19.0 x64

**Comment by hallaathrad** [comment]
Anyway we can help? would love to open a PR if you have any clues on what needs to be fixed.

**Comment by Fred-Barclay** [comment]
G'day @hallaathrad 
Thanks for the report and sorry for the trouble. It looks like our pty.js binaries aren't compatible with the version of Electron shipped with Atom 1.19. Upstream has released new builds, but they're having trouble with them (see https://github.com/platformio/platformio-atom-ide-terminal/issues/297 and https://github.com/platformio/platformio-atom-ide-terminal/issues/304).

At the moment I plan on keeping a close eye on our platformio upstream and pushing a patch ASAP. Certainly though if you beat me to it a PR would be welcome. :)

Cheers!

**Comment by hallaathrad** [comment]
Hey :) thanks for the quick response. 
Managed to rebuild the package manually by doing
```
cd ~/.atom/packages/termination/node_modules/pty.js
apm rebuild
```

Reload atom after that and you should be fine.
If not, this at least seems to enable the "rebuild package" button, which should solve the issue as well.

Working on submitting a PR with the updated package.

**Comment by Fred-Barclay** [comment]
Hopefully it's fixed now with the 0.6.0 release. After updating, Atom may tell you to rebuild Termination due to incompatibilities... just click the red bug icon and follow the prompts.

**Comment by jsolisu** [comment]
@Fred-Barclay Sorry, but it is not fixed on 0.6.0 release. 
Atom 1.20.0 x64

**Comment by Fred-Barclay** [comment]
@jsolisu Sorry about that. I'll take a look, but since 1.20.0 is still beta I most likely will not push a fix until it reaches stable.
