### ISSUE TITLE
Since Atom update to 1.19.0 Termination fails to create terminals on Windows 7

### ISSUE THREAD

**Issue by tsela** [Fred-Barclay/Termination#58]
Since the latest Atom update, Termination fails to work properly. The UI is still present, as well as the key bindings and commands, but the area where the terminal window should appear stays empty, with a blinking cursor on the top left-hand corner, rather than showing the Windows Powershell appearing. It's possible to create more instances of that terminal window, to close them and reopen them as normal, they just stay empty and thus unusable.

Issue may be related to #57 (although in this case, the UI is still working, it just won't actually open a terminal window) and #56.

Atom version: 1.19.0 x64
Termination version: 0.5.1
OS: Windows 7 Enterprise Service Pack 1 x64
Steps to reproduce the issue:
1. Open Atom version 1.19
2. Try opening a terminal either by clicking on the + button or using a keybinding or a command
3. See the terminal window open as in the attached picture, but no terminal actually starts, and input is impossible
4. Notice that closing and opening the instance is still possible, but it stays empty
![terminationissue](https://user-images.githubusercontent.com/475638/29159672-aea2151a-7daf-11e7-80d1-5c5df666409c.PNG)

**Comment by AStupidBear** [comment]
I have the same issue.

**Comment by BenoitRanque** [comment]
Same issue here on Windows 10, Atom 1.19.0 x64

**Comment by Fred-Barclay** [comment]
Sorry about this mates. I'm hoping to get a fix out shortly.

**Comment by Fred-Barclay** [comment]
Hopefully it's fixed now with the 0.6.0 release. After updating, Atom may tell you to rebuild Termination due to incompatibilities... just click the red bug icon and follow the prompts.

**Comment by BenoitRanque** [comment]
Can confirm this is now solved after updating package, clicking bug icon, rebuilding and reloading.

**Comment by iovo79** [comment]
Still facing the problem in 
Windows 7 professional Sp1 
x64.

Any updates ?

**Comment by Fred-Barclay** [comment]
@iovo79 are you running the latest release of Termination (0.7.1) and the latest Atom?

**Comment by iovo79** [comment]
Yes 
I use Atom 1.34.0 
and Termination 0.7.1

PS. thanks for the fast reply
